require("dotenv").config();
const express=require("express"), path=require("path"), crypto=require("crypto"), bcrypt=require("bcryptjs"), multer=require("multer"), {Pool}=require("pg"), session=require("express-session"), PgStore=require("connect-pg-simple")(session), OpenAI=require("openai"), fs=require("fs");
const app=express(), PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
async function db(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,email text UNIQUE NOT NULL,password_hash text NOT NULL,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS plans(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,goal text default '',text text default '',updated_at timestamptz default now());
CREATE TABLE IF NOT EXISTS progress(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,tests int default 0,correct int default 0,total int default 0);
CREATE TABLE IF NOT EXISTS tests(id uuid PRIMARY KEY,user_id uuid REFERENCES users(id) ON DELETE CASCADE,title text,payload jsonb,created_at timestamptz default now());`)}
db().catch(console.error);
app.use(express.json({limit:"2mb"}));app.use(express.urlencoded({extended:true}));
app.use(session({store:new PgStore({pool,createTableIfMissing:true}),secret:process.env.SESSION_SECRET||"change-me",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:7*24*3600*1000}}));
const upload=multer({dest:path.join(__dirname,"uploads"),limits:{fileSize:8*1024*1024}});
function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:"Bạn cần đăng nhập."});next()}
function ai(){if(!process.env.OPENAI_API_KEY)throw Error("OPENAI_API_KEY chưa được cấu hình");return new OpenAI({apiKey:process.env.OPENAI_API_KEY})}
app.get("/api/health",async(req,res)=>{try{await pool.query("select 1");res.json({ok:true,version:"16"})}catch(e){res.status(500).json({ok:false})}});
app.get("/api/me",(req,res)=>res.json({user:req.session.userId?{id:req.session.userId,email:req.session.email}:null}));
app.post("/api/register",async(req,res)=>{try{let email=String(req.body.email||"").trim().toLowerCase(),pw=String(req.body.password||"");if(!email||pw.length<6)return res.status(400).json({error:"Email và mật khẩu tối thiểu 6 ký tự."});let exists=await pool.query("select 1 from users where email=$1",[email]);if(exists.rowCount)return res.status(409).json({error:"Tài khoản đã tồn tại."});let id=crypto.randomUUID(),hash=await bcrypt.hash(pw,12);await pool.query("insert into users(id,email,password_hash) values($1,$2,$3)",[id,email,hash]);req.session.userId=id;req.session.email=email;res.json({message:"Đăng ký thành công."})}catch(e){res.status(500).json({error:"Không thể đăng ký lúc này."})}});
app.post("/api/login",async(req,res)=>{try{let email=String(req.body.email||"").trim().toLowerCase(),pw=String(req.body.password||"");let q=await pool.query("select * from users where email=$1",[email]);if(!q.rowCount||!(await bcrypt.compare(pw,q.rows[0].password_hash)))return res.status(401).json({error:"Sai email hoặc mật khẩu."});req.session.userId=q.rows[0].id;req.session.email=email;res.json({message:"Đăng nhập thành công."})}catch(e){res.status(500).json({error:"Không thể đăng nhập lúc này."})}});
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.post("/api/tutor",auth,upload.single("image"),async(req,res)=>{try{let client=ai(),subject=req.body.subject||"môn học",mode=req.body.mode||"giải thích",msg=req.body.message||"";let input=`Bạn là gia sư AI cho học sinh Việt Nam ôn thi chuyên. Môn ${subject}. Chế độ ${mode}. Trả lời bằng tiếng Việt, rõ ràng, không bịa. Nếu là bài tập, trình bày từng bước phù hợp học sinh. Câu hỏi: ${msg}`;if(req.file)input+="\nHọc sinh có gửi ảnh bài tập. Nếu hệ thống/model không thể đọc ảnh trực tiếp, hãy nói rõ và yêu cầu học sinh chép phần đề cần thiết.";let out=await client.responses.create({model:process.env.OPENAI_MODEL,input});res.json({answer:out.output_text||"Không có câu trả lời."})}catch(e){res.status(500).json({error:e.message})}finally{if(req.file)fs.unlink(req.file.path,()=>{})}});
app.post("/api/generate-test",auth,async(req,res)=>{try{let client=ai(),subject=req.body.subject||"Toán",level=req.body.level||"Chuyên",count=Math.min(20,Math.max(1,Number(req.body.count)||5)),minutes=Math.min(180,Math.max(5,Number(req.body.minutes)||30));let schema=`{"title":"...","instructions":"...","minutes":${minutes},"questions":[{"question":"...","options":["...","...","...","..."],"answer":0,"explanation":"..."}]}`;let prompt=`Tạo đề thi chuyên hoàn toàn mới bằng tiếng Việt. Môn ${subject}, mức ${level}, ${count} câu, ${minutes} phút. Không sao chép nguyên văn đề có sẵn. Mỗi câu 4 lựa chọn. Chỉ trả JSON hợp lệ theo mẫu ${schema}.`;let out=await client.responses.create({model:process.env.OPENAI_MODEL,input:prompt});let txt=out.output_text.trim().replace(/^```json\s*/,"").replace(/```$/,"").trim(),test=JSON.parse(txt);test.questions=(test.questions||[]).slice(0,count);let id=crypto.randomUUID();await pool.query("insert into tests(id,user_id,title,payload) values($1,$2,$3,$4)",[id,req.session.userId,test.title,JSON.stringify(test)]);res.json({test})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/plan",auth,async(req,res)=>{let q=await pool.query("select goal,text from plans where user_id=$1",[req.session.userId]);res.json(q.rows[0]||{goal:"",text:""})});
app.post("/api/plan",auth,async(req,res)=>{await pool.query(`insert into plans(user_id,goal,text) values($1,$2,$3) on conflict(user_id) do update set goal=excluded.goal,text=excluded.text,updated_at=now()`,[req.session.userId,String(req.body.goal||""),String(req.body.text||"")]);res.json({ok:true})});
app.get("/api/progress",auth,async(req,res)=>{let q=await pool.query("select tests,correct,total from progress where user_id=$1",[req.session.userId]);res.json(q.rows[0]||{tests:0,correct:0,total:0})});
app.post("/api/progress",auth,async(req,res)=>{let c=Number(req.body.correct)||0,t=Number(req.body.total)||0;await pool.query(`insert into progress(user_id,tests,correct,total) values($1,1,$2,$3) on conflict(user_id) do update set tests=progress.tests+1,correct=progress.correct+$2,total=progress.total+$3`,[req.session.userId,c,t]);res.json({ok:true})});
app.use(express.static(path.join(__dirname,"public")));
app.use((req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("Thi Chuyen AI V16 running on port "+PORT));